### ISSUE TITLE
Cannot import in Typescript

### ISSUE THREAD

**Issue by st-clair-clarke** [a-synchronous/rubico#185]
Hi,
I cant seem to import rubico using Typescript. Is there Typescript definition types?

**Comment by richytong** [comment]
There's no Typescript definitions at the moment, but I think it's worth looking into it. I think I need help with this because I don't use Typescript in my day-to-day, and my guess is there's some gotchas to implementing type definitions for rubico? I'm not really sure. Do you know if it's feasible off the top of your head?

**Comment by lulldev** [comment]
interesting task. soon i try create some types for core. but many questions

@richytong for example in pipe we must provide referential transparency for each function. for example:

pipe([
  someAsync, // return Promise with typed value
  handle, // this function must have typed arg same as previous result.
])

in similar cases need to strategize types. in one of variant it will be like `fp-ts` with algebras or some with light-weight generic types.

**Comment by lulldev** [comment]
@richytong hello my friend! 

i want to start create ts types and one of ideas: create @types/rubico in https://github.com/DefinitelyTyped/DefinitelyTyped

what you think about it? and maybe you want collect types in your repo?

**Comment by richytong** [comment]
@lulldev hello sir it's going to be challenging because rubico has an already very amorphous API and it's going to get even more so in the coming months with eager versions of all the functions, optional function/nonfunction arguments, and optional Promise handling with nonfunction arguments. I would delay doing any types until these API changes stabilize, then maybe we can tackle TypeScript

**Comment by richytong** [comment]
`rubico` should be usable with TypeScript now.
