### ISSUE TITLE
Curiosity - why the name rubico?

### ISSUE THREAD

**Issue by maxdevjs** [a-synchronous/rubico#63]
Isn't `Rubicon` or, even better, `Rubicone`? Isn't `Rubico` a [revolver-styled](https://warframe.fandom.com/wiki/Rubico) Tenno?

**Comment by richytong** [comment]
Originally I was gonna go for rubicon (inspired randomly from blacklist) but it was taken on `npm`. Then I just went latin with it so that's how it goes. Also a nice plus that it was actually a river.

I did see that link. I hope one day rubico the library and rubico the revolver-styled Tenno can coexist, like two guys named John.

**Comment by maxdevjs** [comment]
I see, deft solution. Thank you for the explanation.
